# Generated by Django 5.1.6 on 2025-02-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
