# Generated by Django 5.1.6 on 2025-02-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_name_alter_event_registration_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinEcellRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=20)),
                ('course_branch', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('field_of_interest', models.TextField()),
                ('role_preference', models.CharField(choices=[('domain_leader', 'Domain Leader'), ('management_team', 'Management Team')], max_length=20)),
                ('has_experience', models.BooleanField(default=False)),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('portfolio_links', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('value_proposition', models.TextField()),
                ('time_commitment', models.CharField(choices=[('1-3', '1-3 hours per week'), ('4-6', '4-6 hours per week'), ('7+', '7+ hours per week')], max_length=3)),
                ('team_work_comfort', models.BooleanField(default=False)),
                ('has_startup_ideas', models.BooleanField(default=False)),
                ('startup_ideas_description', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
