# Generated by Django 5.1.6 on 2025-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_joinecellregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinecellregistration',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='joinecellregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='joinecellregistration',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
