# Generated by Django 5.1.6 on 2025-02-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_joinecellregistration_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinecellregistration',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
