# Generated by Django 5.1.6 on 2025-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_joinecellregistration_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='certificate_sent',
            field=models.BooleanField(default=False),
        ),
    ]
