# Generated by Django 5.1.6 on 2025-02-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_certificate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='certificate_sent',
        ),
    ]
