# Generated by Django 5.1.6 on 2025-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
