# Generated by Django 5.1.6 on 2025-02-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(choices=[('FACULTY', 'Faculty Advisors'), ('DOMAIN', 'Domain Leaders'), ('MANAGEMENT', 'Management Team')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('course_year', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
