# Generated by Django 5.1.6 on 2025-02-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
