# Generated by Django 5.1.6 on 2025-02-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
