# Generated by Django 5.1.6 on 2025-02-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0002_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon_name',
        ),
    ]
