# Generated by Django 5.1.6 on 2025-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0003_remove_socialmedia_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='icon_name',
        ),
    ]
