# Generated by Django 5.1.6 on 2025-02-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0004_remove_initiative_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cta_text',
        ),
    ]
