# Generated by Django 5.1.6 on 2025-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecellpage', '0005_remove_event_cta_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Igniting Entrepreneurial Spirit at MMDU', max_length=255)),
                ('buttonText', models.CharField(default='Explore Programs', max_length=50)),
                ('buttonLink', models.CharField(default='#', max_length=255)),
                ('taglinedescription', models.TextField(default="E-Cell MMDU fosters innovation and business leadership through mentorship, resources, and startup opportunities. Join us to shape tomorrow's industry leaders.")),
                ('initiativesLink', models.CharField(default='#', max_length=255)),
                ('initiativesText', models.CharField(default='Our Initiatives', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
